name: jsfasdf
description: ''
version: 0.0.1
author: kiranadmin@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: jsfasdf
  parentArtefactID: kiranadminprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2023-10-09 06:28:26'
pipelines:
  pipelines/p1:
    name: p1
    description: fgagdasg2334
    author: kiranadmin@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-10-09 06:29:06'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
functions:
  author: null
  createdAt: '2023-10-09 06:28:26'
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '34936':
    projectUID: 34936
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/wD3Rheoe_team_8768/wD3Rheoe_project_34936.git&subPath=
    version: 0.0.2
    isDefault: true
    author: null
    createdAt: '2023-10-09 06:27:34'
  '34935':
    projectUID: 34935
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/wD3Rheoe_team_8768/wD3Rheoe_project_34935.git&subPath=
    version: 0.0.4
    isDefault: true
    author: null
    createdAt: '2023-10-09 06:27:34'
pipelineConfigurations: {}
